package com.example.bankcards.dto.card;

import com.example.bankcards.service.model.enums.CardStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Data
@Schema(
    description = "Response payload containing the details of a newly issued bank card."
)
public class CreateCardResponseDto {

    @Schema(
        description = "The masked credit/debit card number generated by the system.",
        example = "4312 8900 1122 3344"
    )
    private String cardNumber;

    @Schema(
        description = "The unique identifier of the card.",
        example = "123e4567-e89b-12d3-a456-426614174000"
    )
    private UUID uuid;

    @Schema(
        description = "The full name of the cardholder in capital Latin letters.",
        example = "JOHN DOE"
    )
    private String holderName;

    @Schema(
        description = "The calculated expiration timestamp for the issued bank card.",
        example = "2031-08-13T16:50:00Z"
    )
    private Instant expiryDate;

    @Schema(
        description = "The initial operational status assigned to the new card.",
        example = "ACTIVE"
    )
    private CardStatus status;

    @Schema(
        description = "The initial financial balance allocated to the card upon creation.",
        example = "0.00"
    )
    private BigDecimal balance;
}
